import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream

=======
import { ViewTransitions } from "next-view-transitions";
import { RootProvider } from "fumadocs-ui/provider";
import { ThemeProvider } from "next-themes";
>>>>>>> Stashed changes
=======
import { ViewTransitions } from "next-view-transitions";
import { RootProvider } from "fumadocs-ui/provider";
import { ThemeProvider } from "next-themes";
>>>>>>> Stashed changes
=======
import { ViewTransitions } from "next-view-transitions";
import { RootProvider } from "fumadocs-ui/provider";
import { ThemeProvider } from "next-themes";
>>>>>>> Stashed changes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  title: "Create Next App",
=======
  title: "GlintKitUI",
>>>>>>> Stashed changes
=======
  title: "GlintKitUI",
>>>>>>> Stashed changes
=======
  title: "GlintKitUI",
>>>>>>> Stashed changes
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <RootProvider>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            <div className="flex flex-col min-h-screen">
              <div className="flex-1">{children}</div>
            </div>
            </ThemeProvider>
          </RootProvider>
        </body>
      </html>
    </ViewTransitions>
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
  );
}
